PASSENGERS_SINGULAR = [
    "passenger",
    "traveller",
    "person",
    "friend",
    "colleague",
    "family member",
    "companion",
    "co-traveler",
    "guest",
    "tourist",
    "individual",
    "rider",
    "customer",
    "client",
    "associate",
    "group member",
    "party member",
    "voyager",
    "commuter",
    "relative",
    "partner",
    "acquaintance"
]

PASSENGERS_PLURAL = [
    "passengers",
    "travellers",
    "people",
    "friends",
    "colleagues",
    "family members",
    "companions",
    "co-travelers",
    "guests",
    "tourists",
    "individuals",
    "riders",
    "customers",
    "clients",
    "associates",
    "group members",
    "party members",
    "voyagers",
    "commuters",
    "relatives",
    "partners",
    "acquaintances"
]