STATIONS = [
    "Abbey Wood",
    "Aber",
    "Aberaeron",
    "Abercynon",
    "Aberdare",
    "Aberdeen",
    "Aberdour",
    "Aberdovey",
    "Abererch",
    "Abergavenny",
    "Abergele & Pensarn",
    "Aberystwyth",
    "Accrington",
    "Achanalt",
    "Achnasheen",
    "Achnashellach",
    "Acklington",
    "Acle",
    "Acocks Green",
    "Acton (Any)",
    "Acton Bridge (Cheshire)",
    "Acton Central",
    "Acton Main Line",
    "Adderley Park",
    "Addiewell",
    "Addlestone",
    "Adisham",
    "Adlington (Cheshire)",
    "Adlington (Lancashire)",
    "Adwick",
    "Aigburth",
    "Ainsdale",
    "Aintree",
    "Airbles",
    "Airdrie",
    "Albany Park",
    "Albrighton",
    "Alderley Edge",
    "Aldermaston",
    "Aldershot",
    "Aldrington",
    "Alexandra Palace",
    "Alexandra Parade",
    "Alexandria",
    "Alfreton",
    "Allens West",
    "Alloa",
    "Alness",
    "Alnmouth",
    "Alresford (Essex)",
    "Alsager",
    "Althorne (Essex)",
    "Althorpe",
    "Altnabreac",
    "Alton",
    "Alton Towers (Any)",
    "Altrincham",
    "Alvechurch",
    "Ambergate",
    "Amberley",
    "Amersham",
    "Ammanford",
    "Ancaster",
    "Anderston",
    "Andover",
    "Anerley",
    "Angmering",
    "Annan",
    "Anniesland",
    "Ansdell & Fairhaven",
    "Apperley Bridge",
    "Appleby",
    "Appledore (Kent)",
    "Appleford",
    "Appley Bridge",
    "Apsley",
    "Arbroath",
    "Ardgay",
    "Ardlui",
    "Ardrossan (Any)",
    "Ardrossan Harbour",
    "Ardrossan South Beach",
    "Ardrossan Town",
    "Ardwick",
    "Argyle Street",
    "Arisaig",
    "Arlesey",
    "Armadale (West Lothian)",
    "Armathwaite",
    "Arnside",
    "Arram",
    "Arrochar & Tarbet",
    "Arundel",
    "Ascot (Berks)",
    "Ascott-under-Wychwood",
    "Ash",
    "Ash Vale",
    "Ashburys",
    "Ashchurch for Tewkesbury",
    "Ashfield",
    "Ashford (Surrey)",
    "Ashford International",
    "Ashley",
    "Ashtead",
    "Ashton-under-Lyne",
    "Ashurst (Kent)",
    "Ashurst New Forest",
    "Ashwell & Morden",
    "Askam",
    "Aslockton",
    "Aspatria",
    "Aspley Guise",
    "Aston",
    "Atherstone",
    "Atherton",
    "Attadale",
    "Attenborough",
    "Attleborough",
    "Auchinleck",
    "Audley End",
    "Aughton Park",
    "Aviemore",
    "Avoncliff",
    "Avonmouth",
    "Axminster",
    "Aylesbury",
    "Aylesbury Vale Parkway",
    "Aylesford",
    "Aylesham",
    "Ayr",
    "Bache",
    "Baglan",
    "Bagshot",
    "Baildon",
    "Baillieston",
    "Balcombe",
    "Baldock",
    "Balham",
    "Balloch",
    "Balmossie",
    "Bamber Bridge",
    "Bamford",
    "Banavie",
    "Banbury",
    "Bangor (Gwynedd)",
    "Bank Hall",
    "Banstead",
    "Barassie",
    "Bardon Mill",
    "Bare Lane",
    "Bargeddie",
    "Bargoed",
    "Barking",
    "Barking Riverside",
    "Barlaston",
    "Barming",
    "Barmouth",
    "Barnehurst",
    "Barnes",
    "Barnes (Any)",
    "Barnes Bridge",
    "Barnetby",
    "Barnham",
    "Barnhill",
    "Barnsley",
    "Barnstaple",
    "Barnt Green",
    "Barrhead",
    "Barrhill",
    "Barrow Haven",
    "Barrow-in-Furness",
    "Barrow-upon-Soar",
    "Barry",
    "Barry (Any)",
    "Barry Docks",
    "Barry Island",
    "Barry Links",
    "Barton-on-Humber",
    "Basildon",
    "Basingstoke",
    "Bat & Ball",
    "Bath Spa",
    "Bathgate",
    "Batley",
    "Battersby",
    "Battersea (Any)",
    "Battersea Park",
    "Battle",
    "Battlesbridge",
    "Bayford",
    "Beaconsfield",
    "Bearley",
    "Bearsden",
    "Bearsted",
    "Beasdale",
    "Beaulieu Road",
    "Beauly",
    "Bebington",
    "Beccles",
    "Beckenham (Any)",
    "Beckenham Hill",
    "Beckenham Junction",
    "Bedford",
    "Bedford (Any)",
    "Bedford St Johns",
    "Bedhampton",
    "Bedminster",
    "Bedworth",
    "Bedwyn",
    "Beeston",
    "Bekesbourne",
    "Belfast Lanyon Place",
    "Belfast Port",
    "Belford Bus",
    "Belle Vue",
    "Bellgrove",
    "Bellingham",
    "Bellshill",
    "Belmont",
    "Belper",
    "Beltring",
    "Belvedere",
    "Bempton",
    "Ben Rhydding",
    "Benfleet",
    "Bentham",
    "Bentley (Hampshire)",
    "Bentley (South Yorkshire)",
    "Bere Alston",
    "Bere Ferrers",
    "Berkhamsted",
    "Berkswell",
    "Bermuda Park",
    "Berney Arms",
    "Berry Brow",
    "Berrylands",
    "Berwick (Sussex)",
    "Berwick-upon-Tweed",
    "Bescar Lane",
    "Bescot Stadium",
    "Betchworth",
    "Bethnal Green",
    "Betws-y-Coed",
    "Beverley",
    "Bexhill",
    "Bexley",
    "Bexleyheath",
    "Bicester (Any)",
    "Bicester North",
    "Bicester Village",
    "Bickley",
    "Bidston",
    "Biggleswade",
    "Bilbrook",
    "Billericay",
    "Billingham",
    "Billingshurst",
    "Bingham",
    "Bingley",
    "Birchgrove",
    "Birchington-on-Sea",
    "Birchwood",
    "Birkbeck",
    "Birkdale",
    "Birkenhead (Any)",
    "Birkenhead Central",
    "Birkenhead Hamilton Square",
    "Birkenhead North",
    "Birkenhead Park",
    "Birmingham (Any)",
    "Birmingham International",
    "Birmingham Moor Street",
    "Birmingham New Street",
    "Birmingham Snow Hill",
    "Bishop Auckland",
    "Bishopbriggs",
    "Bishops Stortford",
    "Bishopstone (Sussex)",
    "Bishopton (Renfrewshire)",
    "Bitterne",
    "Blackburn",
    "Blackheath",
    "Blackhorse Road",
    "Blackpool (Any)",
    "Blackpool North",
    "Blackpool Pleasure Beach",
    "Blackpool South",
    "Blackridge",
    "Blackrod",
    "Blackwater",
    "Blackwood Bus",
    "Blaenau Ffestiniog",
    "Blair Atholl",
    "Blairhill",
    "Blake Street",
    "Blakedown",
    "Blantyre",
    "Blaydon",
    "Bleasby",
    "Bletchley",
    "Bloxwich",
    "Bloxwich (Any)",
    "Bloxwich North",
    "Blundellsands & Crosby",
    "Blythe Bridge",
    "Bodmin Parkway",
    "Bodorgan",
    "Bognor Regis",
    "Bogston",
    "Bolton",
    "Bolton-upon-Dearne",
    "Bond Street (Elizabeth line)",
    "Bookham",
    "Bootle (Any)",
    "Bootle (Cumbria)",
    "Bootle New Strand",
    "Bootle Oriel Road",
    "Bordesley",
    "Borough Green & Wrotham",
    "Borth",
    "Bosham",
    "Boston",
    "Botley",
    "Bottesford",
    "Bourne End",
    "Bournemouth",
    "Bournville",
    "Bow Brickhill",
    "Bow Street",
    "Bowes Park",
    "Bowling",
    "Box Hill & Westhumble",
    "Bracknell",
    "Bradford (Any)",
    "Bradford Forster Square",
    "Bradford Interchange",
    "Bradford-on-Avon",
    "Brading",
    "Braintree",
    "Braintree Freeport",
    "Bramhall",
    "Bramley (Hampshire)",
    "Bramley (West Yorkshire)",
    "Brampton (Cumbria)",
    "Brampton (Suffolk)",
    "Branchton",
    "Brandon",
    "Branksome",
    "Braystones",
    "Bredbury",
    "Breich",
    "Brent Cross West",
    "Brentford",
    "Brentwood",
    "Bricket Wood",
    "Bridge of Allan",
    "Bridge of Orchy",
    "Bridgend",
    "Bridgeton",
    "Bridgwater",
    "Bridlington",
    "Brierfield",
    "Brigg",
    "Brighouse",
    "Brighton",
    "Brighton (Any)",
    "Brimsdown",
    "Brinnington",
    "Bristol Airport (By Bus)",
    "Bristol Parkway",
    "Bristol Temple Meads",
    "Brithdir",
    "Briton Ferry",
    "Brixton",
    "Broad Green",
    "Broadbottom",
    "Broadstairs",
    "Brockenhurst",
    "Brockholes",
    "Brockley",
    "Brockley Whins",
    "Brodick (Arran)",
    "Bromborough",
    "Bromborough (Any)",
    "Bromborough Rake",
    "Bromley (Any)",
    "Bromley Cross (Lancs)",
    "Bromley North",
    "Bromley South",
    "Bromsgrove",
    "Brondesbury",
    "Brondesbury (Any)",
    "Brondesbury Park",
    "Brookmans Park",
    "Brookwood",
    "Broome",
    "Broomfleet",
    "Brora",
    "Brough",
    "Broughty Ferry",
    "Broxbourne",
    "Bruce Grove",
    "Brundall",
    "Brundall (Any)",
    "Brundall Gardens",
    "Brunstane",
    "Brunswick",
    "Bruton",
    "Bryn",
    "Buckenham",
    "Buckley",
    "Bucknell",
    "Buckshaw Parkway",
    "Bude Bus",
    "Bugle",
    "Builth Road",
    "Bulwell",
    "Bures",
    "Burgess Hill",
    "Burley Park",
    "Burley-in-Wharfedale",
    "Burnage",
    "Burneside (Cumbria)",
    "Burnham (Buckinghamshire)",
    "Burnham-on-Crouch",
    "Burnley (Any)",
    "Burnley Barracks",
    "Burnley Central",
    "Burnley Manchester Road",
    "Burnside (South Lanarkshire)",
    "Burntisland",
    "Burscough (Any)",
    "Burscough Bridge",
    "Burscough Junction",
    "Bursledon",
    "Burton Joyce",
    "Burton-on-Trent",
    "Bury St Edmunds",
    "Busby",
    "Bush Hill Park",
    "Bushey",
    "Butlers Lane",
    "Buxted",
    "Buxton",
    "Buxton (Any)",
    "Byfleet & New Haw",
    "Bynea",
    "Cadoxton",
    "Caergwrle",
    "Caerphilly",
    "Caersws",
    "Cairnryan",
    "Caldercruix",
    "Caldicot",
    "Caledonian Road & Barnsbury",
    "Calstock",
    "Cam & Dursley",
    "Camberley",
    "Camborne",
    "Cambridge",
    "Cambridge Heath",
    "Cambridge North",
    "Cambuslang",
    "Camden Road",
    "Camelon",
    "Canada Water",
    "Canary Wharf (Elizabeth line)",
    "Canley",
    "Cannock",
    "Canonbury",
    "Canterbury (Any)",
    "Canterbury East",
    "Canterbury West",
    "Cantley",
    "Capenhurst",
    "Carbis Bay",
    "Cardenden",
    "Cardiff (Any)",
    "Cardiff Air Ria",
    "Cardiff Bay",
    "Cardiff Central",
    "Cardiff Queen Street",
    "Cardonald",
    "Cardross",
    "Carfin",
    "Cark & Cartmel",
    "Carlisle",
    "Carlton",
    "Carluke",
    "Carmarthen",
    "Carmyle",
    "Carnforth",
    "Carnoustie",
    "Carntyne",
    "Carpenders Park",
    "Carrbridge",
    "Carshalton",
    "Carshalton Beeches",
    "Carstairs",
    "Cartsdyke",
    "Castle Bar Park",
    "Castle Cary",
    "Castlebay (Barra)",
    "Castleford",
    "Castleton (Manchester)",
    "Castleton Moor",
    "Caterham",
    "Catford",
    "Catford (Any)",
    "Catford Bridge",
    "Cathays",
    "Cathcart",
    "Cattal",
    "Catterick Garrison Bus",
    "Causeland",
    "Cefn-y-Bedd",
    "Chadwell Heath",
    "Chafford Hundred Lakeside",
    "Chalfont & Latimer",
    "Chalkwell",
    "Chandlers Ford",
    "Chapel-en-le-Frith",
    "Chapelton (Devon)",
    "Chapeltown (South Yorkshire)",
    "Chappel & Wakes Colne",
    "Charing (Kent)",
    "Charing Cross (Glasgow)",
    "Charlbury",
    "Charlton",
    "Chartham",
    "Chassen Road",
    "Chatelherault",
    "Chatham",
    "Chathill",
    "Cheadle Hulme",
    "Cheam",
    "Cheddington",
    "Chelford (Cheshire)",
    "Chelmsford",
    "Chelsfield",
    "Cheltenham Spa",
    "Chepstow",
    "Cherry Tree",
    "Chertsey",
    "Cheshunt",
    "Chessington (Any)",
    "Chessington North",
    "Chessington South",
    "Chester",
    "Chester Road",
    "Chester-le-Street",
    "Chesterfield",
    "Chestfield & Swalecliffe",
    "Chetnole",
    "Chichester",
    "Chilham",
    "Chilworth",
    "Chingford",
    "Chinley",
    "Chippenham",
    "Chipstead",
    "Chirk",
    "Chislehurst",
    "Chiswick",
    "Cholsey",
    "Chorley",
    "Chorleywood",
    "Christchurch",
    "Christs Hospital",
    "Church & Oswaldtwistle",
    "Church Fenton",
    "Church Stretton",
    "Cilmeri",
    "City Thameslink",
    "Clacton-on-Sea",
    "Clandon",
    "Clapham (North Yorkshire)",
    "Clapham High Street",
    "Clapham Junction",
    "Clapton",
    "Clarbeston Road",
    "Clarkston",
    "Claverdon",
    "Claygate",
    "Cleethorpes",
    "Cleland",
    "Clifton (Manchester)",
    "Clifton Down",
    "Clitheroe",
    "Clock House",
    "Clunderwen",
    "Clydebank",
    "Coatbridge (Any)",
    "Coatbridge Central",
    "Coatbridge Sunnyside",
    "Coatdyke",
    "Cobham & Stoke D'Abernon",
    "Codsall",
    "Cogan",
    "Colchester",
    "Colchester (Any)",
    "Colchester Town",
    "Coleshill Parkway",
    "Collingham",
    "Collington",
    "Colne",
    "Colwall",
    "Colwyn Bay",
    "Combe (Oxon)",
    "Commondale",
    "Congleton",
    "Conisbrough",
    "Connel Ferry",
    "Conon Bridge",
    "Cononley",
    "Conway Park",
    "Conwy",
    "Cooden Beach",
    "Cookham",
    "Cooksbridge",
    "Coombe Junction Halt",
    "Copplestone",
    "Corbridge",
    "Corby",
    "Corby-Peterborough (By Bus)",
    "Corkerhill",
    "Corkickle",
    "Corpach",
    "Corrour",
    "Coryton",
    "Coseley",
    "Cosford",
    "Cosham",
    "Cottingham",
    "Cottingley",
    "Coulsdon South",
    "Coulsdon Town",
    "Coventry",
    "Coventry Arena",
    "Cowden (Kent)",
    "Cowdenbeath",
    "Cradley Heath",
    "Craigendoran",
    "Craignure (Mull)",
    "Cramlington",
    "Cranbrook (Devon)",
    "Craven Arms",
    "Crawley",
    "Crayford",
    "Crediton",
    "Cressing (Essex)",
    "Cressington",
    "Creswell",
    "Crewe",
    "Crewkerne",
    "Crews Hill",
    "Crianlarich",
    "Criccieth",
    "Cricklewood",
    "Croftfoot",
    "Crofton Park",
    "Cromer",
    "Cromford",
    "Crookston",
    "Cross Gates",
    "Crossflatts",
    "Crosshill",
    "Crosskeys",
    "Crossmyloof",
    "Croston",
    "Crouch Hill",
    "Crowborough",
    "Crowhurst",
    "Crowle",
    "Crowthorne",
    "Croxley",
    "Croy",
    "Croydon (Any)",
    "Crystal Palace",
    "Cuddington",
    "Cuffley",
    "Culham",
    "Culrain",
    "Cumbernauld",
    "Cumbrae",
    "Cupar",
    "Curriehill",
    "Custom House (Elizabeth line)",
    "Cuxton",
    "Cwmbach",
    "Cwmbran",
    "Cynghordy",
    "Dagenham Dock",
    "Daisy Hill",
    "Dalgety Bay",
    "Dalmally",
    "Dalmarnock",
    "Dalmeny",
    "Dalmuir",
    "Dalreoch",
    "Dalry",
    "Dalston (Cumbria)",
    "Dalston Junction",
    "Dalston Kingsland",
    "Dalton (Cumbria)",
    "Dalwhinnie",
    "Danby",
    "Danescourt",
    "Danzey",
    "Darlington",
    "Darnall",
    "Darsham",
    "Dartford",
    "Dartmouth",
    "Darton",
    "Darwen",
    "Datchet",
    "Davenport",
    "Dawlish",
    "Dawlish Warren",
    "Deal",
    "Dean (Wilts)",
    "Deansgate",
    "Deganwy",
    "Deighton",
    "Delamere",
    "Denby Dale",
    "Denham",
    "Denham Golf Club",
    "Denmark Hill",
    "Dent",
    "Denton",
    "Deptford",
    "Derby",
    "Derby Road (Ipswich)",
    "Dereham Coach",
    "Devonport",
    "Dewsbury",
    "Didcot Parkway",
    "Digby & Sowton",
    "Dilton Marsh",
    "Dinas (Rhondda)",
    "Dinas Powys",
    "Dingle Road",
    "Dingwall",
    "Dinsdale",
    "Dinting",
    "Disley",
    "Diss",
    "Dockyard (Devonport)",
    "Dodworth",
    "Dolau",
    "Doleham",
    "Dolgarrog",
    "Dolwyddelan",
    "Doncaster",
    "Dorchester (Any)",
    "Dorchester South",
    "Dorchester West",
    "Dore & Totley",
    "Dorking (Any)",
    "Dorking (Deepdene)",
    "Dorking (Main)",
    "Dorking West",
    "Dormans",
    "Dorridge",
    "Douglas (Isle of Man)",
    "Dove Holes",
    "Dover Priory",
    "Dovercourt",
    "Dovey Junction",
    "Downham Market",
    "Drayton Green",
    "Drayton Park",
    "Drem",
    "Driffield",
    "Drigg",
    "Droitwich Spa",
    "Dronfield",
    "Drumchapel",
    "Drumfrochar",
    "Drumgelloch",
    "Drumry",
    "Dublin (Any)",
    "Dublin Connolly",
    "Dublin Ferryport",
    "Dublin Heuston",
    "Dublin Port - Stena",
    "Duddeston",
    "Dudley (Any)",
    "Dudley Port",
    "Duffield",
    "Duirinish",
    "Duke Street",
    "Dullingham",
    "Dulwich (Any)",
    "Dumbarton (Any)",
    "Dumbarton Central",
    "Dumbarton East",
    "Dumbreck",
    "Dumfries",
    "Dumpton Park",
    "Dunbar",
    "Dunblane",
    "Duncraig",
    "Dundee",
    "Dunfermline (Any)",
    "Dunfermline City",
    "Dunfermline Queen Margaret",
    "Dunkeld & Birnam",
    "Dunlop",
    "Dunoon",
    "Dunrobin Castle",
    "Duns",
    "Dunster Bus",
    "Dunston",
    "Dunton Green",
    "Durham",
    "Durrington-on-Sea",
    "Dyce",
    "Dyffryn Ardudwy",
    "Eaglescliffe",
    "Ealing (Any)",
    "Ealing Broadway",
    "Earlestown",
    "Earley",
    "Earlsfield",
    "Earlston",
    "Earlswood (Surrey)",
    "Earlswood (West Midlands)",
    "East Boldon",
    "East Cowes",
    "East Croydon",
    "East Didsbury",
    "East Dulwich",
    "East Farleigh",
    "East Garforth",
    "East Grinstead",
    "East Kilbride",
    "East Malling",
    "East Midlands Parkway",
    "East Tilbury",
    "East Worthing",
    "Eastbourne",
    "Eastbrook",
    "Easterhouse",
    "Eastham Rake",
    "Eastleigh",
    "Eastrington",
    "Ebbsfleet International",
    "Ebbw Vale Parkway",
    "Ebbw Vale Town",
    "Eccles (Manchester)",
    "Eccles Road",
    "Eccleston Park",
    "Edale",
    "Eden Park",
    "Edenbridge (Any)",
    "Edenbridge (Kent)",
    "Edenbridge Town",
    "Edge Hill",
    "Edinburgh (Waverley)",
    "Edinburgh Airport (By Bus or Tram)",
    "Edinburgh Gateway",
    "Edinburgh Park",
    "Edmonton Green",
    "Effingham Junction",
    "Eggesford",
    "Egham",
    "Egton",
    "Elephant & Castle",
    "Elgin",
    "Ellesmere Port",
    "Elmers End",
    "Elmstead Woods",
    "Elmswell",
    "Elsecar",
    "Elsenham (Essex)",
    "Elstree & Borehamwood",
    "Eltham",
    "Elton & Orston",
    "Ely",
    "Emerson Park",
    "Emr Destination",
    "Emr Origin",
    "Emsworth",
    "Energlyn & Churchill Park",
    "Enfield (Any)",
    "Enfield Chase",
    "Enfield Lock",
    "Enfield Town",
    "Entwistle",
    "Epsom (Surrey)",
    "Epsom Downs",
    "Erdington",
    "Eridge",
    "Eridge (A26 Bus Stop)",
    "Erith",
    "Esher",
    "Eskbank",
    "Essex Road",
    "Etchingham",
    "Euxton Balshaw Lane",
    "Evesham",
    "Ewell (Any)",
    "Ewell East",
    "Ewell West",
    "Exeter (Any)",
    "Exeter Central",
    "Exeter St David's",
    "Exeter St Thomas",
    "Exhibition Centre (Glasgow)",
    "Exmouth",
    "Exton",
    "Eynsford",
    "Fairbourne",
    "Fairfield",
    "Fairlie",
    "Fairwater",
    "Falconwood",
    "Falkirk (Any)",
    "Falkirk Grahamston",
    "Falkirk High",
    "Falls of Cruachan",
    "Falmer",
    "Falmouth (Any)",
    "Falmouth Docks",
    "Falmouth Town",
    "Fareham",
    "Farnborough (Any)",
    "Farnborough (Main)",
    "Farnborough North",
    "Farncombe",
    "Farnham",
    "Farningham Road",
    "Farnworth",
    "Farringdon",
    "Fauldhouse",
    "Faversham",
    "Faygate",
    "Fazakerley",
    "Fearn",
    "Featherstone",
    "Felixstowe",
    "Fellgate Metro",
    "Feltham",
    "Feniton",
    "Fenny Stratford",
    "Fernhill",
    "Ferriby",
    "Ferryside",
    "Ffairfach",
    "Filey",
    "Filton Abbey Wood",
    "Finchley Road & Frognal",
    "Finsbury Park",
    "Finstock",
    "Fishbourne (Sussex)",
    "Fishersgate",
    "Fishguard & Goodwick",
    "Fishguard Harbour",
    "Fiskerton",
    "Fitzwilliam",
    "Five Ways",
    "Fleet",
    "Flimby",
    "Flint",
    "Flitwick",
    "Flixton",
    "Flowery Field",
    "Folkestone (Any)",
    "Folkestone Central",
    "Folkestone West",
    "Ford",
    "Forest Gate",
    "Forest Hill",
    "Formby",
    "Forres",
    "Forsinard",
    "Fort Matilda",
    "Fort William",
    "Four Oaks",
    "Foxfield",
    "Foxford",
    "Foxton",
    "Frant",
    "Fratton",
    "Freshfield",
    "Freshford",
    "Frimley",
    "Frinton-on-Sea",
    "Frizinghall",
    "Frodsham",
    "Frome",
    "Fulwell",
    "Furness Vale",
    "Furze Platt",
    "Gainsborough (Any)",
    "Gainsborough Central",
    "Gainsborough Lea Road",
    "Galashiels",
    "Galashiels Bus Station",
    "Garelochhead",
    "Garforth",
    "Gargrave",
    "Garrowhill",
    "Garscadden",
    "Garsdale",
    "Garston (Hertfordshire)",
    "Garswood",
    "Gartcosh",
    "Garth (Mid Glamorgan)",
    "Garth (Powys)",
    "Garve",
    "Gathurst",
    "Gatley",
    "Gatwick Airport",
    "Georgemas Junction",
    "Gerrards Cross",
    "Gidea Park",
    "Giffnock",
    "Giggleswick",
    "Gilberdyke",
    "Gilfach Fargoed",
    "Gillingham (Dorset)",
    "Gillingham (Kent)",
    "Gilshochill",
    "Gipsy Hill",
    "Girvan",
    "Glaisdale",
    "Glan Conwy",
    "Glasgow (Any)",
    "Glasgow Central",
    "Glasgow Queen Street",
    "Glasshoughton",
    "Glazebrook",
    "Gleneagles",
    "Glenfinnan",
    "Glengarnock",
    "Glenrothes With Thornton",
    "Glossop",
    "Gloucester",
    "Glynde",
    "Gobowen",
    "Godalming",
    "Godley",
    "Godstone",
    "Goldthorpe",
    "Golf Street",
    "Golspie",
    "Gomshall",
    "Goodmayes",
    "Goole",
    "Goostrey",
    "Gordon Hill",
    "Gorebridge",
    "Goring & Streatley",
    "Goring-by-Sea",
    "Gorton",
    "Gospel Oak",
    "Gourock",
    "Gowerton",
    "Goxhill",
    "Grange Park",
    "Grange-over-Sands",
    "Grangetown (Cardiff)",
    "Grantham",
    "Grateley",
    "Gravelly Hill",
    "Gravesend",
    "Grays",
    "Great Ayton",
    "Great Bentley",
    "Great Chesterford",
    "Great Coates",
    "Great Malvern",
    "Great Missenden",
    "Great Yarmouth",
    "Green Lane",
    "Green Road",
    "Greenbank",
    "Greenfaulds",
    "Greenfield",
    "Greenford",
    "Greenford (Any)",
    "Greenhithe for Bluewater",
    "Greenock (Any)",
    "Greenock Central",
    "Greenock West",
    "Greenwich",
    "Gretna Green",
    "Grimsby (Any)",
    "Grimsby Docks",
    "Grimsby Town",
    "Grindleford",
    "Grosmont",
    "Grove Park",
    "Guide Bridge",
    "Guildford",
    "Guildford (Any)",
    "Guiseley",
    "Gunnersbury",
    "Gunnislake",
    "Gunton",
    "Gwersyllt",
    "Gypsy Lane",
    "Habrough",
    "Hackbridge",
    "Hackney (Any)",
    "Hackney Central",
    "Hackney Downs",
    "Hackney Wick",
    "Haddenham & Thame Parkway",
    "Haddiscoe",
    "Hadfield",
    "Hadley Wood",
    "Hag Fold",
    "Haggerston",
    "Hagley",
    "Hairmyres",
    "Hale (Manchester)",
    "Halesworth",
    "Halewood",
    "Halifax",
    "Hall Green",
    "Hall Road",
    "Hall-i-th-Wood",
    "Halling",
    "Haltwhistle",
    "Ham Street",
    "Hamble",
    "Hamilton (Any)",
    "Hamilton Central",
    "Hamilton West",
    "Hammerton",
    "Hampden Park (Sussex)",
    "Hampstead (Any)",
    "Hampstead Heath",
    "Hampton (London)",
    "Hampton Court",
    "Hampton Wick",
    "Hampton-in-Arden",
    "Hamstead (Birmingham)",
    "Hamworthy",
    "Hanborough",
    "Handforth",
    "Hanwell",
    "Hapton",
    "Harlech",
    "Harlesden",
    "Harling Road",
    "Harlington (Bedfordshire)",
    "Harlow (Any)",
    "Harlow Mill",
    "Harlow Town",
    "Harold Wood",
    "Harpenden",
    "Harrietsham",
    "Harringay",
    "Harringay (Any)",
    "Harringay Green Lanes",
    "Harrington",
    "Harrogate",
    "Harrow & Wealdstone",
    "Harrow (Any)",
    "Harrow-on-the-Hill",
    "Hartford (Cheshire)",
    "Hartlebury",
    "Hartlepool",
    "Hartwood",
    "Harwich (Any)",
    "Harwich International",
    "Harwich Town",
    "Haslemere",
    "Hassocks",
    "Hastings",
    "Hatch End",
    "Hatfield & Stainforth",
    "Hatfield (Herts)",
    "Hatfield Peverel",
    "Hathersage",
    "Hattersley",
    "Hatton",
    "Havant",
    "Havenhouse",
    "Haverfordwest",
    "Hawarden",
    "Hawarden (Any)",
    "Hawarden Bridge",
    "Hawkhead",
    "Haydon Bridge",
    "Haydons Road",
    "Hayes & Harlington",
    "Hayes (Kent)",
    "Hayle",
    "Haymarket",
    "Haywards Heath",
    "Hazel Grove",
    "Headcorn",
    "Headingley",
    "Headstone Lane",
    "Heald Green",
    "Healing",
    "Heath (Any)",
    "Heath High Level",
    "Heath Low Level",
    "Heathrow Airport (Any)",
    "Heathrow Bus (Any)",
    "Heathrow Terminal 2 (Any)",
    "Heathrow Terminal 3 (Any)",
    "Heathrow Terminal 4 (Any)",
    "Heathrow Terminal 4 (Rail Station Only)",
    "Heathrow Terminal 5 (Any)",
    "Heathrow Terminal 5 (Rail Station Only)",
    "Heathrow Terminals 2 & 3 (Rail Station only)",
    "Heathrow Underground",
    "Heaton Chapel",
    "Hebden Bridge",
    "Heckington",
    "Hedge End",
    "Hednesford",
    "Heighington",
    "Helensburgh (Any)",
    "Helensburgh Central",
    "Helensburgh Upper",
    "Hellifield",
    "Helmsdale",
    "Helsby",
    "Helston Bus",
    "Hemel Hempstead",
    "Hendon",
    "Hengoed",
    "Henley-in-Arden",
    "Henley-on-Thames",
    "Hensall",
    "Hereford",
    "Herne Bay",
    "Herne Hill",
    "Hersham",
    "Hertford (Any)",
    "Hertford East",
    "Hertford North",
    "Hessle",
    "Heswall",
    "Hever",
    "Heworth",
    "Hexham",
    "Heyford",
    "Heysham Port",
    "High Brooms",
    "High Street (Glasgow)",
    "High Wycombe",
    "Higham",
    "Highams Park",
    "Highbridge & Burnham",
    "Highbury & Islington",
    "Hightown",
    "Hildenborough",
    "Hillfoot",
    "Hillington (Any)",
    "Hillington East",
    "Hillington West",
    "Hillside",
    "Hilsea",
    "Hinchley Wood",
    "Hinckley (Leics)",
    "Hindley",
    "Hinton Admiral",
    "Hitchin",
    "Hither Green",
    "Hockley",
    "Hollingbourne",
    "Holmes Chapel",
    "Holmwood",
    "Holsworthy Church (Bus)",
    "Holton Heath",
    "Holyhead",
    "Holytown",
    "Homerton",
    "Honeybourne",
    "Honiton",
    "Honley",
    "Honor Oak Park",
    "Hook",
    "Hooton",
    "Hope (Derbyshire)",
    "Hope (Flintshire)",
    "Hopton Heath",
    "Horden",
    "Horley",
    "Hornbeam Park",
    "Hornsey",
    "Horsforth",
    "Horsham",
    "Horsley",
    "Horton-in-Ribblesdale",
    "Horwich Parkway",
    "Hoscar",
    "Hough Green",
    "Hounslow",
    "Hove",
    "Hoveton & Wroxham",
    "How Wood (Hertfordshire)",
    "Howden",
    "Howwood (Renfrewshire)",
    "Hoxton",
    "Hoylake",
    "Hubberts Bridge",
    "Hucknall",
    "Huddersfield",
    "Hull",
    "Humphrey Park",
    "Huncoat",
    "Hungerford",
    "Hunmanby",
    "Hunstanton Bus",
    "Huntingdon",
    "Huntly",
    "Hunts Cross",
    "Hurst Green",
    "Hutton Cranswick",
    "Huyton",
    "Hyde (Any)",
    "Hyde Central",
    "Hyde North",
    "Hykeham",
    "Hyndland",
    "Hythe (Essex)",
    "Idridgehay",
    "Ifield",
    "Ilford",
    "Ilkeston",
    "Ilkley",
    "Imperial Wharf",
    "Ince & Elton (Cheshire)",
    "Ince (Manchester)",
    "Ingatestone",
    "Insch",
    "Invergordon",
    "Invergowrie",
    "Inverkeithing",
    "Inverkip",
    "Inverness",
    "Inverness Airport",
    "Inverness Airport Bus Stance",
    "Invershin",
    "Inverurie",
    "Ipswich",
    "Irlam",
    "Irvine",
    "Isleworth",
    "Islip",
    "Iver",
    "Ivybridge",
    "James Cook University Hospital",
    "Jewellery Quarter",
    "Johnston (Pembs)",
    "Johnstone (Strathclyde)",
    "Jordanhill",
    "Kearsley (Manchester)",
    "Kearsney (Kent)",
    "Keighley",
    "Keith",
    "Kelvedon",
    "Kelvindale",
    "Kemble",
    "Kempston Hardwick",
    "Kempton Park",
    "Kemsing",
    "Kemsley",
    "Kendal",
    "Kenilworth",
    "Kenley",
    "Kennett",
    "Kennishead",
    "Kensal Green",
    "Kensal Rise",
    "Kensington Olympia",
    "Kent House",
    "Kentish Town",
    "Kentish Town (Any)",
    "Kentish Town West",
    "Kenton",
    "Kenton (Any)",
    "Kents Bank",
    "Kettering",
    "Kettering (By Bus via Peterborough)",
    "Kew (Any)",
    "Kew Bridge",
    "Kew Gardens",
    "Keyham",
    "Keynsham",
    "Kidbrooke",
    "Kidderminster",
    "Kidsgrove",
    "Kidwelly",
    "Kilburn High Road",
    "Kildale",
    "Kildonan",
    "Kilgetty",
    "Kilmarnock",
    "Kilmaurs",
    "Kilpatrick",
    "Kilwinning",
    "Kinbrace",
    "Kingham",
    "Kinghorn",
    "Kings Langley",
    "Kings Lynn",
    "Kings Lynn Bus Station",
    "Kings Norton",
    "Kings Nympton",
    "Kings Park",
    "Kings Sutton",
    "Kingsknowe",
    "Kingston",
    "Kingswear (for Dartmouth)",
    "Kingswood",
    "Kingussie",
    "Kintbury",
    "Kintore",
    "Kirby Cross",
    "Kirk Sandall",
    "Kirkby (Merseyside)",
    "Kirkby Stephen",
    "Kirkby-in-Ashfield",
    "Kirkby-in-Furness",
    "Kirkcaldy",
    "Kirkconnel",
    "Kirkdale",
    "Kirkham & Wesham",
    "Kirkhill",
    "Kirknewton",
    "Kirkstall Forge",
    "Kirkwood",
    "Kirton Lindsey",
    "Kiveton (Any)",
    "Kiveton Bridge",
    "Kiveton Park",
    "Knaresborough",
    "Knebworth",
    "Knighton",
    "Knockholt",
    "Knottingley",
    "Knucklas",
    "Knutsford",
    "Kyle of Lochalsh",
    "Ladybank",
    "Ladywell",
    "Laindon",
    "Lairg",
    "Lake",
    "Lakenheath",
    "Lampeter",
    "Lamphey",
    "Lanark",
    "Lancaster",
    "Lancing",
    "Landywood",
    "Langbank",
    "Langho",
    "Langley (Berks)",
    "Langley Green",
    "Langley Mill",
    "Langside",
    "Langwathby",
    "Langwith-Whaley Thorns",
    "Lapford",
    "Lapworth",
    "Larbert",
    "Largs",
    "Larkhall",
    "Laurencekirk",
    "Lawrence Hill",
    "Layton (Lancs)",
    "Lazonby & Kirkoswald",
    "Lea Bridge",
    "Lea Green",
    "Lea Hall",
    "Leagrave",
    "Lealholm",
    "Leamington Spa",
    "Leasowe",
    "Leatherhead",
    "Ledbury",
    "Lee (London)",
    "Leeds",
    "Leeds Bradford Airport",
    "Leicester",
    "Leigh (Kent)",
    "Leigh-on-Sea",
    "Leighton Buzzard",
    "Lelant",
    "Lelant (Any)",
    "Lelant Saltings",
    "Lenham",
    "Lenzie",
    "Leominster",
    "Letchworth Garden City",
    "Leuchars",
    "Levenshulme",
    "Lewes",
    "Lewisham",
    "Leyland",
    "Leyton (Any)",
    "Leyton Midland Road",
    "Leytonstone High Road",
    "Lichfield (Any)",
    "Lichfield City",
    "Lichfield Trent Valley",
    "Lidlington",
    "Limehouse",
    "Lincoln",
    "Lingfield",
    "Lingwood",
    "Linlithgow",
    "Liphook",
    "Liskeard",
    "Liss",
    "Lisvane & Thornhill",
    "Little Kimble",
    "Little Sutton",
    "Littleborough",
    "Littlehampton",
    "Littlehaven",
    "Littleport",
    "Liverpool (Any)",
    "Liverpool Airport Bus",
    "Liverpool Central",
    "Liverpool James Street",
    "Liverpool Lime Street",
    "Liverpool South Parkway",
    "Livingston (Any)",
    "Livingston North",
    "Livingston South",
    "Llanaber",
    "Llanbedr",
    "Llanbister Road",
    "Llanbradach",
    "Llandaf",
    "Llandanwg",
    "Llandecwyn",
    "Llandeilo",
    "Llandovery",
    "Llandrindod",
    "Llandudno",
    "Llandudno Junction",
    "Llandybie",
    "Llanelli",
    "Llanfairfechan",
    "Llanfairpwll",
    "Llangadog",
    "Llangammarch",
    "Llangennech",
    "Llangynllo",
    "Llanharan",
    "Llanhilleth",
    "Llanishen",
    "Llanrwst",
    "Llansamlet",
    "Llantwit Major",
    "Llanwrda",
    "Llanwrtyd",
    "Llwyngwril",
    "Llwynypia",
    "Loch Awe",
    "Loch Eil Outward Bound",
    "Lochailort",
    "Lochboisdale",
    "Locheilside",
    "Lochgelly",
    "Lochluichart",
    "Lochwinnoch",
    "Lockerbie",
    "Lockwood",
    "London (Any)",
    "London Blackfriars",
    "London Bridge",
    "London Cannon Street",
    "London Charing Cross",
    "London Euston",
    "London Fenchurch Street",
    "London Fields",
    "London Kings Cross",
    "London Liverpool Street",
    "London Marylebone",
    "London Paddington",
    "London Road (Brighton)",
    "London Road (Guildford)",
    "London St Pancras International",
    "London Underground Zone 1 (Any)",
    "London Underground Zone 1-2 (Any)",
    "London Underground Zone 1-3 (Any)",
    "London Underground Zone 1-4 (Any)",
    "London Underground Zone 1-5 (Any)",
    "London Underground Zone 1-6 (Any)",
    "London Underground Zone 2-6 (Any)",
    "London Underground Zone 3-6 (Any)",
    "London Underground Zone 4-6 (Any)",
    "London Underground Zone 5-6 (Any)",
    "London Victoria",
    "London Waterloo",
    "London Waterloo East",
    "Long Buckby",
    "Long Eaton",
    "Long Preston",
    "Longbeck",
    "Longbridge",
    "Longcross",
    "Longfield",
    "Longniddry",
    "Longport",
    "Longton",
    "Looe",
    "Lostock",
    "Lostock Gralam",
    "Lostock Hall",
    "Lostwithiel",
    "Loughborough",
    "Loughborough Junction",
    "Low Moor",
    "Lowdham",
    "Lower Sydenham",
    "Lowestoft",
    "Ludlow",
    "Luton",
    "Luton Airport",
    "Luton Airport Parkway",
    "Luxulyan",
    "Lydney",
    "Lye (West Midlands)",
    "Lymington (Any)",
    "Lymington Pier",
    "Lymington Town",
    "Lympstone (Any)",
    "Lympstone Commando",
    "Lympstone Village",
    "Lytham",
    "MIRA Technology Park",
    "Macclesfield",
    "Machynlleth",
    "Maesteg",
    "Maesteg (Any)",
    "Maesteg (Ewenny Road)",
    "Maghull",
    "Maghull North",
    "Maiden Newton",
    "Maidenhead",
    "Maidstone (Any)",
    "Maidstone Barracks",
    "Maidstone East",
    "Maidstone West",
    "Malden Manor",
    "Mallaig",
    "Malling (Any)",
    "Malton",
    "Malvern (Any)",
    "Malvern Link",
    "Manchester (Any)",
    "Manchester Airport",
    "Manchester Central Zone",
    "Manchester Oxford Road",
    "Manchester Piccadilly",
    "Manchester Victoria",
    "Manea",
    "Manningtree",
    "Manor Park",
    "Manor Road",
    "Manorbier",
    "Manors",
    "Mansfield",
    "Mansfield (Any)",
    "Mansfield Woodhouse",
    "March",
    "Marden (Kent)",
    "Margate",
    "Market Harborough",
    "Market Rasen",
    "Markinch",
    "Marks Tey",
    "Marlow",
    "Marple",
    "Marsden (Yorks)",
    "Marsh Barton",
    "Marske",
    "Marston Green",
    "Martin Mill",
    "Martins Heron",
    "Marton",
    "Maryhill",
    "Maryland",
    "Maryport",
    "Matlock",
    "Matlock (Any)",
    "Matlock Bath",
    "Mauldeth Road",
    "Maxwell Park",
    "Maybole",
    "Maze Hill",
    "Meadowhall",
    "Meldreth",
    "Melksham",
    "Melrose",
    "Melton (Suffolk)",
    "Melton Mowbray",
    "Menheniot",
    "Menston",
    "Meols",
    "Meols Cop",
    "Meopham",
    "Meridian Water",
    "Merryton",
    "Merstham",
    "Merthyr Tydfil",
    "Merthyr Vale",
    "Metheringham",
    "Metrocentre",
    "Mexborough",
    "Micheldever",
    "Micklefield",
    "Middlesbrough",
    "Middlewood",
    "Midgham",
    "Midleton",
    "Milford (Surrey)",
    "Milford Haven",
    "Mill Hill (Lancs)",
    "Mill Hill Broadway",
    "Millbrook (Bedfordshire)",
    "Millbrook (Hants)",
    "Milliken Park",
    "Millom",
    "Mills Hill (Manchester)",
    "Milngavie",
    "Milton Keynes Central",
    "Minehead Bus",
    "Minffordd",
    "Minster",
    "Mirfield",
    "Mistley",
    "Mitcham Eastfields",
    "Mitcham Junction",
    "Mobberley",
    "Monifieth",
    "Monks Risborough",
    "Montpelier",
    "Montrose",
    "Moorfields",
    "Moorgate",
    "Moorside",
    "Moorthorpe",
    "Morar",
    "Morchard Road",
    "Morden South",
    "Morecambe",
    "Moreton (Dorset)",
    "Moreton (Merseyside)",
    "Moreton-in-Marsh",
    "Morfa Mawddach",
    "Morley",
    "Morpeth",
    "Mortimer",
    "Mortlake",
    "Moses Gate",
    "Moss Side",
    "Mossley (Manchester)",
    "Mossley Hill",
    "Mosspark",
    "Moston",
    "Motherwell",
    "Motspur Park",
    "Mottingham",
    "Mottisfont & Dunbridge",
    "Mouldsworth",
    "Moulsecoomb",
    "Mount Florida",
    "Mount Vernon",
    "Mountain Ash",
    "Muir of Ord",
    "Muirend",
    "Musselburgh",
    "Mytholmroyd",
    "Nafferton",
    "Nailsea & Backwell",
    "Nairn",
    "Nantwich",
    "Narberth",
    "Narborough",
    "Navigation Road",
    "Neath",
    "Needham Market",
    "Neilston",
    "Nelson",
    "Neston",
    "Netherfield",
    "Nethertown",
    "Netley",
    "New Barnet",
    "New Beckenham",
    "New Brighton",
    "New Clee",
    "New Cross",
    "New Cross (Any)",
    "New Cross Gate",
    "New Cumnock",
    "New Eltham",
    "New Holland",
    "New Hythe",
    "New Lane",
    "New Malden",
    "New Mills (Any)",
    "New Mills Central",
    "New Mills Newtown",
    "New Milton",
    "New Pudsey",
    "New Southgate",
    "Newark (Any)",
    "Newark Castle",
    "Newark Northgate",
    "Newbridge",
    "Newbury",
    "Newbury (Any)",
    "Newbury Racecourse",
    "Newcastle",
    "Newcastle Airport",
    "Newcourt",
    "Newcraighall",
    "Newhaven (Any)",
    "Newhaven Harbour",
    "Newhaven Town",
    "Newington",
    "Newmarket",
    "Newport (Essex)",
    "Newport (South Wales)",
    "Newquay",
    "Newstead",
    "Newton (Lanark)",
    "Newton Abbot",
    "Newton Aycliffe",
    "Newton St Cyres",
    "Newton for Hyde",
    "Newton-le-Willows",
    "Newton-on-Ayr",
    "Newtongrange",
    "Newtonmore",
    "Newtown (Powys)",
    "Ninian Park",
    "Nitshill",
    "Norbiton",
    "Norbury",
    "Normans Bay",
    "Normanton",
    "North Berwick",
    "North Camp",
    "North Dulwich",
    "North Fambridge",
    "North Llanrwst",
    "North Queensferry",
    "North Road (Darlington)",
    "North Sheen",
    "North Walsham",
    "North Wembley",
    "Northallerton",
    "Northampton",
    "Northfield",
    "Northfleet",
    "Northolt Park",
    "Northumberland Park (London)",
    "Northwich",
    "Norwich",
    "Norwood (Any)",
    "Norwood Junction",
    "Nottingham",
    "Nth Destination",
    "Nth Origin",
    "Nuneaton",
    "Nunhead",
    "Nunthorpe",
    "Nutbourne",
    "Nutfield",
    "Oakengates",
    "Oakham",
    "Oakleigh Park",
    "Oban",
    "Ockendon",
    "Ockley",
    "Okehampton",
    "Okehampton (By Bus)",
    "Old Hill",
    "Old Roan",
    "Old Street",
    "Oldfield Park",
    "Oldham (Any)",
    "Olton",
    "Ore",
    "Ormskirk",
    "Orpington",
    "Orrell",
    "Orrell Park",
    "Otford",
    "Oulton Broad (Any)",
    "Oulton Broad North",
    "Oulton Broad South",
    "Oundle Pb Bus",
    "Outwood",
    "Overpool",
    "Overton",
    "Oxenholme Lake District",
    "Oxford",
    "Oxford Parkway",
    "Oxford Westgate",
    "Oxshott",
    "Oxted",
    "Paddock Wood",
    "Padgate",
    "Padstow (By Bus)",
    "Paignton",
    "Paisley (Any)",
    "Paisley Canal",
    "Paisley Gilmour Street",
    "Paisley St James",
    "Palmers Green",
    "Pangbourne",
    "Pannal",
    "Pantyffynnon",
    "Par",
    "Parbold",
    "Park Street",
    "Parkstone (Dorset)",
    "Parson Street",
    "Partick",
    "Parton",
    "Patchway",
    "Patricroft",
    "Patterton",
    "Peartree",
    "Peckham (Any)",
    "Peckham Rye",
    "Pegswood",
    "Pemberton",
    "Pembrey & Burry Port",
    "Pembroke",
    "Pembroke (Any)",
    "Pembroke Dock",
    "Pen-y-Bont",
    "Penally",
    "Penarth",
    "Pencoed",
    "Pengam",
    "Penge (Any)",
    "Penge East",
    "Penge West",
    "Penhelig",
    "Penistone",
    "Penkridge",
    "Penmaenmawr",
    "Penmere",
    "Penrhiwceiber",
    "Penrhyndeudraeth",
    "Penrith (North Lakes)",
    "Penryn (Cornwall)",
    "Pensarn (Gwynedd)",
    "Penshurst",
    "Pentre-Bach",
    "Penychain",
    "Penyffordd",
    "Penzance",
    "Perranwell",
    "Perry Barr",
    "Pershore",
    "Perth",
    "Peterborough",
    "Petersfield",
    "Petts Wood",
    "Pevensey & Westham",
    "Pevensey (Any)",
    "Pevensey Bay",
    "Pewsey",
    "Pickering Bus",
    "Pilning",
    "Pinhoe",
    "Pitlochry",
    "Pitsea",
    "Pleasington",
    "Plockton",
    "Pluckley",
    "Plumley",
    "Plumpton",
    "Plumstead",
    "Plymouth",
    "Pokesdown",
    "Polegate",
    "Polesworth",
    "Pollokshaws (Any)",
    "Pollokshaws East",
    "Pollokshaws West",
    "Pollokshields (Any)",
    "Pollokshields East",
    "Pollokshields West",
    "Polmont",
    "Polsloe Bridge",
    "Ponders End",
    "Pont-y-Pant",
    "Pontarddulais",
    "Pontefract (Any)",
    "Pontefract Baghill",
    "Pontefract Monkhill",
    "Pontefract Tanshelf",
    "Pontlottyn",
    "Pontyclun",
    "Pontypool & New Inn",
    "Pontypridd",
    "Poole",
    "Poppleton",
    "Port Glasgow",
    "Port Sunlight",
    "Port Talbot Parkway",
    "Portchester",
    "Porth",
    "Porthmadog",
    "Portlethen",
    "Portslade",
    "Portsmouth & Southsea",
    "Portsmouth (Any)",
    "Portsmouth Arms",
    "Portsmouth Harbour",
    "Portway Park & Ride",
    "Possilpark & Parkhouse",
    "Potters Bar",
    "Poulton-le-Fylde",
    "Poynton",
    "Prees",
    "Prescot",
    "Prestatyn",
    "Prestbury",
    "Preston (Lancs)",
    "Preston Park",
    "Prestonpans",
    "Prestwick (Any)",
    "Prestwick International Airport",
    "Prestwick Town",
    "Priesthill & Darnley",
    "Princes Risborough",
    "Prittlewell",
    "Prudhoe",
    "Pulborough",
    "Purfleet",
    "Purley",
    "Purley (Any)",
    "Purley Oaks",
    "Putney",
    "Pwllheli",
    "Pye Corner",
    "Pyle",
    "Quakers Yard",
    "Queenborough",
    "Queens Park (Glasgow)",
    "Queens Park (London)",
    "Queens Road (Peckham)",
    "Queenstown Road",
    "Quintrell Downs",
    "Radcliffe (Nottinghamshire)",
    "Radlett",
    "Radley",
    "Radyr",
    "Rainford",
    "Rainham (Essex)",
    "Rainham (Kent)",
    "Rainhill",
    "Ramsgate",
    "Ramsgreave & Wilpshire",
    "Rannoch",
    "Rauceby",
    "Ravenglass for Eskdale",
    "Ravensbourne",
    "Ravensthorpe",
    "Rawcliffe",
    "Rayleigh",
    "Raynes Park",
    "Reading",
    "Reading (Any)",
    "Reading Green Park",
    "Reading West",
    "Rectory Road",
    "Redbridge",
    "Redcar (Any)",
    "Redcar Central",
    "Redcar East",
    "Reddish (Any)",
    "Reddish North",
    "Reddish South",
    "Redditch",
    "Redhill",
    "Redland",
    "Redruth",
    "Reedham (London)",
    "Reedham (Norfolk)",
    "Reigate",
    "Renton",
    "Reston",
    "Retford",
    "Rhiwbina",
    "Rhoose Cardiff International Airport",
    "Rhosneigr",
    "Rhyl",
    "Rhymney",
    "Ribblehead",
    "Rice Lane",
    "Richmond (London)",
    "Richmond Yks Bus",
    "Rickmansworth",
    "Riddlesdown",
    "Ridgmont",
    "Riding Mill",
    "Risca & Pontymister",
    "Rishton",
    "Robertsbridge",
    "Robroyston",
    "Roby",
    "Rochdale",
    "Roche",
    "Rochester",
    "Rochford",
    "Rock Ferry",
    "Rogart",
    "Rogerstone",
    "Rolleston",
    "Roman Bridge",
    "Romford",
    "Romiley",
    "Romsey",
    "Roose",
    "Rose Grove",
    "Rose Hill Marple",
    "Rosslare Europort",
    "Rosyth",
    "Rotherham Central",
    "Rotherhithe",
    "Rothesay (Bute)",
    "Roughton Road",
    "Rowlands Castle",
    "Rowley Regis",
    "Roy Bridge",
    "Roydon",
    "Royston",
    "Ruabon",
    "Rufford",
    "Rugby",
    "Rugeley (Any)",
    "Rugeley Town",
    "Rugeley Trent Valley",
    "Ruislip (Any)",
    "Runcorn",
    "Runcorn (Any)",
    "Runcorn East",
    "Ruskington",
    "Ruswarp",
    "Rutherglen",
    "Ryde (Any)",
    "Ryde Esplanade",
    "Ryde Hoverport",
    "Ryde Pier Head",
    "Ryde St Johns Road",
    "Ryder Brow",
    "Rye (Sussex)",
    "Rye House",
    "Salford (Any)",
    "Salford Central",
    "Salford Crescent",
    "Salfords (Surrey)",
    "Salhouse",
    "Salisbury",
    "Saltaire",
    "Saltash",
    "Saltburn",
    "Saltcoats",
    "Saltmarshe",
    "Salwick",
    "Sandal & Agbrigg",
    "Sandbach",
    "Sanderstead",
    "Sandhills",
    "Sandhurst (Berks)",
    "Sandling",
    "Sandown",
    "Sandplace",
    "Sandwell & Dudley",
    "Sandwich",
    "Sandy",
    "Sankey For Penketh",
    "Sanquhar",
    "Sarn",
    "Saundersfoot",
    "Saunderton",
    "Sawbridgeworth",
    "Saxilby",
    "Saxmundham",
    "Scarborough",
    "Scotscalder",
    "Scotstounhill",
    "Scunthorpe",
    "Sea Mills",
    "Seaburn",
    "Seaford (Sussex)",
    "Seaforth & Litherland",
    "Seaham",
    "Seahouses Bus",
    "Seamer",
    "Seascale",
    "Seaton Carew",
    "Seer Green & Jordans",
    "Selby",
    "Selhurst",
    "Sellafield",
    "Selling",
    "Selly Oak",
    "Settle",
    "Seven Kings",
    "Seven Sisters",
    "Sevenoaks",
    "Severn Beach",
    "Severn Tunnel Junction",
    "Shadwell",
    "Shalford (Surrey)",
    "Shanklin",
    "Shawfair",
    "Shawford",
    "Shawlands",
    "Sheerness-on-Sea",
    "Sheffield",
    "Shelford (Cambs)",
    "Shenfield",
    "Shenstone",
    "Shepherd's Bush",
    "Shepherds Well",
    "Shepley",
    "Shepperton",
    "Shepreth",
    "Sherborne",
    "Sherburn-in-Elmet",
    "Sheringham",
    "Shettleston",
    "Shieldmuir",
    "Shifnal",
    "Shildon",
    "Shiplake",
    "Shipley (Yorks)",
    "Shippea Hill",
    "Shipton",
    "Shirebrook",
    "Shirehampton",
    "Shireoaks",
    "Shirley",
    "Shoeburyness",
    "Sholing",
    "Shoreditch High Street",
    "Shoreham (Kent)",
    "Shoreham-by-Sea",
    "Shortlands",
    "Shottle",
    "Shotton",
    "Shotts",
    "Shrewsbury",
    "Sidcup",
    "Sileby",
    "Silecroft",
    "Silkstone Common",
    "Silver Street",
    "Silverdale",
    "Singer",
    "Sittingbourne",
    "Skegness",
    "Skewen",
    "Skipton",
    "Skye (Armadale)",
    "Slade Green",
    "Slaithwaite",
    "Slateford",
    "Sleaford",
    "Sleights",
    "Slough",
    "Small Heath",
    "Smallbrook Junction",
    "Smethwick (Any)",
    "Smethwick Galton Bridge",
    "Smethwick Rolfe Street",
    "Smithy Bridge",
    "Snaith",
    "Snodland",
    "Snowdown",
    "Soham",
    "Sole Street",
    "Solihull",
    "Somerleyton",
    "South Acton",
    "South Bank",
    "South Bermondsey",
    "South Croydon",
    "South Elmsall",
    "South Greenford",
    "South Gyle",
    "South Hampstead",
    "South Kenton",
    "South Merton",
    "South Milford",
    "South Ruislip",
    "South Tottenham",
    "South Wigston",
    "South Woodham Ferrers",
    "Southall",
    "Southampton (Any)",
    "Southampton Airport Parkway",
    "Southampton Central",
    "Southbourne",
    "Southbury",
    "Southease",
    "Southease (Church By bus)",
    "Southend (Any)",
    "Southend Airport",
    "Southend Central",
    "Southend East",
    "Southend Victoria",
    "Southminster",
    "Southport",
    "Southport (Any)",
    "Southsea Hoverport",
    "Southwick",
    "Sowerby Bridge",
    "Spalding",
    "Spean Bridge",
    "Spital",
    "Spondon",
    "Spooner Row",
    "Spring Road",
    "Springburn",
    "Springfield",
    "Squires Gate",
    "St Albans Abbey",
    "St Albans City",
    "St Andrews Bus",
    "St Andrews Road",
    "St Annes-on-the-Sea",
    "St Austell",
    "St Bees",
    "St Budeaux (Any)",
    "St Budeaux Ferry Road",
    "St Budeaux Victoria Road",
    "St Columb Road",
    "St Denys",
    "St Erth",
    "St Germans",
    "St Helens (Any)",
    "St Helens Central",
    "St Helens Junction",
    "St Helier (London)",
    "St Ives (Cornwall)",
    "St James Park (Exeter)",
    "St James Street (Walthamstow)",
    "St Johns (London)",
    "St Keyne Wishing Well Halt",
    "St Leonards (Any)",
    "St Leonards Warrior Square",
    "St Margarets (Herts)",
    "St Margarets (London)",
    "St Mary Cray",
    "St Michaels",
    "St Neots",
    "St Peters",
    "Stadium of Light",
    "Stafford",
    "Staines",
    "Stallingborough",
    "Stalybridge",
    "Stamford (Lincs)",
    "Stamford Hill",
    "Stanford-le-Hope",
    "Stanlow & Thornton",
    "Stansted (Any)",
    "Stansted Airport",
    "Stansted Mountfitchet",
    "Staplehurst",
    "Stapleton Road",
    "Starbeck",
    "Starcross",
    "Staveley (Cumbria)",
    "Stechford",
    "Steeton & Silsden",
    "Stepps",
    "Stevenage",
    "Stevenston",
    "Stewartby",
    "Stewarton",
    "Stirling",
    "Stockport",
    "Stocksfield",
    "Stocksmoor",
    "Stockton",
    "Stoke Mandeville",
    "Stoke Newington",
    "Stoke-on-Trent",
    "Stone (Staffs)",
    "Stone Crossing",
    "Stone Granville Square (Bus)",
    "Stonebridge Park",
    "Stonegate",
    "Stonehaven",
    "Stonehouse",
    "Stoneleigh",
    "Stornoway (Lewis)",
    "Stourbridge (Any)",
    "Stourbridge Junction",
    "Stourbridge Town",
    "Stow",
    "Stowmarket",
    "Stranraer",
    "Stratford (London)",
    "Stratford International",
    "Stratford-upon-Avon",
    "Stratford-upon-Avon Parkway",
    "Strathcarron",
    "Strawberry Hill",
    "Streatham (Any)",
    "Streatham (Greater London)",
    "Streatham Common",
    "Streatham Hill",
    "Streethouse",
    "Strines",
    "Stromeferry",
    "Strood (Kent)",
    "Stroud (Gloucs)",
    "Sturry",
    "Styal",
    "Sudbury & Harrow Road",
    "Sudbury (Suffolk)",
    "Sudbury Hill Harrow",
    "Sugar Loaf",
    "Summerston",
    "Sunbury",
    "Sunderland",
    "Sundridge Park",
    "Sunningdale",
    "Sunnymeads",
    "Surbiton",
    "Surrey Quays",
    "Sutton (London)",
    "Sutton Coldfield",
    "Sutton Common",
    "Sutton Parkway",
    "Swaffham (By Bus)",
    "Swale",
    "Swanley",
    "Swanscombe",
    "Swansea",
    "Swanwick",
    "Sway",
    "Swaythling",
    "Swinderby",
    "Swindon (Wilts)",
    "Swineshead",
    "Swinton (Manchester)",
    "Swinton (South Yorks)",
    "Sydenham (Any)",
    "Sydenham (London)",
    "Sydenham Hill",
    "Syon Lane",
    "Syston",
    "Tackley",
    "Tadworth",
    "Taffs Well",
    "Tain",
    "Tal-y-Cafn",
    "Talsarnau",
    "Talybont",
    "Tame Bridge Parkway",
    "Tamworth",
    "Taplow",
    "Tattenham Corner",
    "Taunton",
    "Taynuilt",
    "Teddington",
    "Teignmouth",
    "Telford Central",
    "Templecombe",
    "Tenby",
    "Teynham",
    "Thames Ditton",
    "Thatcham",
    "Thatto Heath",
    "The Hawthorns",
    "The Lakes (Warks)",
    "Theale",
    "Theobalds Grove",
    "Thetford",
    "Thirsk",
    "Thomastown  (CIV)",
    "Thornaby",
    "Thorne (Any)",
    "Thorne North",
    "Thorne South",
    "Thornford",
    "Thornliebank",
    "Thornton Abbey",
    "Thornton Heath",
    "Thorntonhall",
    "Thorpe Bay",
    "Thorpe Culvert",
    "Thorpe-le-Soken",
    "Three Bridges",
    "Three Oaks",
    "Thurgarton",
    "Thurnscoe",
    "Thurso",
    "Thurston",
    "Tilbury (Any)",
    "Tilbury Riverside",
    "Tilbury Town",
    "Tile Hill",
    "Tilehurst",
    "Tipton",
    "Tir-Phil",
    "Tisbury",
    "Tiverton Parkway",
    "Todmorden",
    "Tolworth",
    "Ton Pentre",
    "Tonbridge",
    "Tondu",
    "Tonfanau",
    "Tonypandy",
    "Tooting",
    "Topsham",
    "Torquay",
    "Torre",
    "Totnes",
    "Tottenham (Any)",
    "Tottenham Court Road (Elizabeth line)",
    "Tottenham Hale",
    "Totton",
    "Town Green",
    "Trafford Park",
    "Trefforest",
    "Trefforest (Any)",
    "Trefforest Estate",
    "Trehafod",
    "Treherbert",
    "Treorchy",
    "Trimley",
    "Tring",
    "Troed-y-rhiw",
    "Troon",
    "Trowbridge",
    "Truro",
    "Tulloch",
    "Tulse Hill",
    "Tunbridge Wells",
    "Turkey Street",
    "Tutbury & Hatton",
    "Tweedbank",
    "Twickenham",
    "Twyford",
    "Ty Croes",
    "Ty Glas",
    "Tygwyn",
    "Tyndrum (Any)",
    "Tyndrum Lower",
    "Tyseley",
    "Tywyn",
    "Uckfield",
    "Uddingston",
    "Ulceby",
    "Ullapool",
    "Ulleskelf",
    "Ulverston",
    "Umberleigh",
    "University (Birmingham)",
    "Uphall",
    "Upholland",
    "Upminster",
    "Upper Halliford",
    "Upper Holloway",
    "Upper Tyndrum",
    "Upper Warlingham",
    "Upton (Merseyside)",
    "Upwey",
    "Urmston",
    "Uttoxeter",
    "Valley",
    "Vauxhall",
    "Virginia Water",
    "Waddon",
    "Wadebridge Bus",
    "Wadhurst",
    "Wainfleet",
    "Wakefield (Any)",
    "Wakefield Kirkgate",
    "Wakefield Westgate",
    "Walkden",
    "Wallasey (Any)",
    "Wallasey Grove Road",
    "Wallasey Village",
    "Wallington",
    "Wallyford",
    "Walmer",
    "Walsall",
    "Walsden",
    "Waltham Cross",
    "Walthamstow (Any)",
    "Walthamstow Central",
    "Walthamstow Queens Road",
    "Walton (Any)",
    "Walton (Merseyside)",
    "Walton-on-Thames",
    "Walton-on-the-Naze",
    "Wanborough",
    "Wandsworth (Any)",
    "Wandsworth Common",
    "Wandsworth Road",
    "Wandsworth Town",
    "Wanstead Park",
    "Wapping",
    "Warblington",
    "Ware (Herts)",
    "Wareham (Dorset)",
    "Wargrave",
    "Warminster",
    "Warnham",
    "Warrington (Any)",
    "Warrington Bank Quay",
    "Warrington Central",
    "Warrington West",
    "Warwick",
    "Warwick Parkway",
    "Water Orton",
    "Waterbeach",
    "Wateringbury",
    "Waterloo (Merseyside)",
    "Watford (Any)",
    "Watford High Street",
    "Watford Junction",
    "Watford North",
    "Watlington",
    "Watton-at-Stone",
    "Waun-Gron Park",
    "Wavertree Technology Park",
    "Wedgwood",
    "Wedgwood Lane",
    "Weeley",
    "Weeton",
    "Welham Green",
    "Welling",
    "Wellingborough",
    "Wellington (Shropshire)",
    "Welshpool",
    "Welwyn (Any)",
    "Welwyn Garden City",
    "Welwyn North",
    "Wem",
    "Wembley (Any)",
    "Wembley Central",
    "Wembley Stadium",
    "Wemyss Bay",
    "Wendover",
    "Wennington",
    "West Allerton",
    "West Brompton",
    "West Byfleet",
    "West Calder",
    "West Cowes",
    "West Croydon",
    "West Drayton",
    "West Dulwich",
    "West Ealing",
    "West Ham",
    "West Hampstead",
    "West Hampstead Thameslink",
    "West Horndon",
    "West Kilbride",
    "West Kirby",
    "West Malling",
    "West Norwood",
    "West Ruislip",
    "West Runton",
    "West St Leonards",
    "West Sutton",
    "West Wickham",
    "West Worthing",
    "Westbury",
    "Westcliff",
    "Westcombe Park",
    "Westenhanger",
    "Wester Hailes",
    "Westerfield",
    "Westerton",
    "Westgate-on-Sea",
    "Westhoughton",
    "Weston Milton",
    "Weston-super-Mare",
    "Wetheral",
    "Weybridge",
    "Weymouth",
    "Whaley Bridge",
    "Whalley (Lancs)",
    "Whatstandwell",
    "Whifflet",
    "Whimple",
    "Whinhill",
    "Whiston",
    "Whitby",
    "Whitby Bus",
    "Whitchurch (Cardiff)",
    "Whitchurch (Hampshire)",
    "Whitchurch (Shropshire)",
    "White Hart Lane",
    "White Notley",
    "Whitechapel",
    "Whitecraigs",
    "Whitehaven",
    "Whitland",
    "Whitley Bridge",
    "Whitlocks End",
    "Whitstable",
    "Whittlesea",
    "Whittlesford Parkway",
    "Whitton (London)",
    "Whitwell (Derbyshire)",
    "Whyteleafe",
    "Whyteleafe (Any)",
    "Whyteleafe South",
    "Wick",
    "Wickford",
    "Wickham Market",
    "Widdrington",
    "Widnes",
    "Widney Manor",
    "Wigan (Any)",
    "Wigan North Western",
    "Wigan Wallgate",
    "Wigton",
    "Wildmill",
    "Willesden Junction",
    "Williamwood",
    "Willington",
    "Wilmcote",
    "Wilmslow",
    "Wilnecote (Staffs)",
    "Wimbledon",
    "Wimbledon (Any)",
    "Wimbledon Chase",
    "Winchelsea",
    "Winchester",
    "Winchfield",
    "Winchmore Hill",
    "Windermere",
    "Windsor & Eton Central",
    "Windsor & Eton Riverside",
    "Winnersh",
    "Winnersh (Any)",
    "Winnersh Triangle",
    "Winsford",
    "Wirksworth",
    "Wisbech (Coach)",
    "Wishaw",
    "Witham",
    "Witley",
    "Witton (West Midlands)",
    "Wivelsfield",
    "Wivenhoe",
    "Woburn Sands",
    "Woking",
    "Wokingham",
    "Woldingham",
    "Wolverhampton",
    "Wolverton",
    "Wombwell",
    "Wood End",
    "Wood Street",
    "Woodbridge",
    "Woodgrange Park",
    "Woodhall",
    "Woodhouse",
    "Woodlesford",
    "Woodley",
    "Woodmansterne",
    "Woodsmoor",
    "Wool",
    "Woolston",
    "Woolwich (Any)",
    "Woolwich (Elizabeth line)",
    "Woolwich Arsenal",
    "Woolwich Dockyard",
    "Wootton Wawen",
    "Worcester (Any)",
    "Worcester Foregate Street",
    "Worcester Park",
    "Worcester Shrub Hill",
    "Worcestershire Parkway",
    "Workington",
    "Worksop",
    "Worle",
    "Worplesdon",
    "Worstead",
    "Worthing",
    "Worthing (Any)",
    "Wrabness",
    "Wraysbury",
    "Wrenbury",
    "Wressle",
    "Wrexham (Any)",
    "Wrexham Central",
    "Wrexham General",
    "Wye",
    "Wylam",
    "Wylde Green",
    "Wymondham",
    "Wythall",
    "Xc Destination",
    "Xc Origin",
    "Yalding",
    "Yardley Wood",
    "Yarm",
    "Yarmouth (Isle of Wight)",
    "Yate",
    "Yatton",
    "Yeoford",
    "Yeovil (Any)",
    "Yeovil Junction",
    "Yeovil Pen Mill",
    "Yetminster",
    "Ynyswen",
    "Yoker",
    "York",
    "Yorton",
    "Ystrad Mynach",
    "Ystrad Rhondda"
]